import { Question } from '@/types';

export const PLACEMENT_50_QUESTIONS: Question[] = [
  // ==========================================
  // PYTHON PROGRAMMING (Questions 1 - 10)
  // ==========================================
  {
    id: 'q_py_1',
    questionText: 'What is the output of the following Python code?\n\nx = [1, 2, 3]\ny = x\ny.append(4)\nprint(x)',
    optionA: '[1, 2, 3]',
    optionB: '[1, 2, 3, 4]',
    optionC: '[4, 1, 2, 3]',
    optionD: 'AttributeError',
    correctAnswer: 'B',
    difficulty: 'Easy',
    subject: 'Python',
    topic: 'List Mutability & References',
    explanation: 'Lists in Python are mutable objects. `y = x` assigns a reference to the same list object in memory, so mutating `y` also modifies `x`.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_py_2',
    questionText: 'Which of the following data structures in Python is immutable?',
    optionA: 'List',
    optionB: 'Dictionary',
    optionC: 'Set',
    optionD: 'Tuple',
    correctAnswer: 'D',
    difficulty: 'Easy',
    subject: 'Python',
    topic: 'Built-in Data Types',
    explanation: 'Tuples are immutable sequences in Python. Once created, their elements cannot be modified, added, or removed.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_py_3',
    questionText: 'What does the `is` operator check in Python?',
    optionA: 'If two variables have equal values',
    optionB: 'If two variables refer to the exact same memory location (identity)',
    optionC: 'If two variables have the same data type',
    optionD: 'If a variable exists in the local scope',
    correctAnswer: 'B',
    difficulty: 'Easy',
    subject: 'Python',
    topic: 'Operators & Object Identity',
    explanation: '`==` checks for value equality, whereas `is` checks for object identity (i.e. whether `id(a) == id(b)`).',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_py_4',
    questionText: 'What is the output of: `print([x**2 for x in range(5) if x % 2 == 0])`?',
    optionA: '[0, 4, 16]',
    optionB: '[0, 1, 4, 9, 16]',
    optionC: '[4, 16]',
    optionD: '[0, 2, 4]',
    correctAnswer: 'A',
    difficulty: 'Easy',
    subject: 'Python',
    topic: 'List Comprehesions',
    explanation: '`range(5)` generates 0, 1, 2, 3, 4. Even numbers are 0, 2, 4. Their squares are 0^2=0, 2^2=4, 4^2=16 -> `[0, 4, 16]`.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_py_5',
    questionText: 'What is the Global Interpreter Lock (GIL) in CPython?',
    optionA: 'A mutex that prevents multiple native threads from executing Python bytecodes at once',
    optionB: 'A security firewall built into Python web frameworks',
    optionC: 'A memory leak prevention algorithm',
    optionD: 'A garbage collector strategy for circular references',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'Python',
    topic: 'Concurrency & GIL',
    explanation: 'The GIL is a lock that allows only one thread to control the Python interpreter at a time, impacting CPU-bound multi-threaded programs.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_py_6',
    questionText: 'What does the `yield` keyword do in Python functions?',
    optionA: 'Exits the function immediately and returns None',
    optionB: 'Pauses function execution and returns a generator object iterator',
    optionC: 'Raises an exception to signal completion',
    optionD: 'Converts a function into an asynchronous coroutine',
    correctAnswer: 'B',
    difficulty: 'Medium',
    subject: 'Python',
    topic: 'Generators & Iterators',
    explanation: '`yield` turns a normal function into a Generator function, preserving its execution state between successive `next()` calls.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_py_7',
    questionText: 'What is the output of: `print("Placement"[::-1])`?',
    optionA: 'Placement',
    optionB: 'tnamecalP',
    optionC: 'tnemecalP',
    optionD: 'IndexError',
    correctAnswer: 'C',
    difficulty: 'Easy',
    subject: 'Python',
    topic: 'String Slicing',
    explanation: '`[::-1]` is the standard Python string slicing technique to reverse a string, yielding `"tnemecalP"`.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_py_8',
    questionText: 'How are `*args` and `**kwargs` used in Python function definitions?',
    optionA: '`*args` passes variable positional arguments, `**kwargs` passes variable keyword arguments',
    optionB: '`*args` passes pointers, `**kwargs` passes reference parameters',
    optionC: '`*args` is for integer lists, `**kwargs` is for floating point numbers',
    optionD: 'Both are reserved keywords for class constructors',
    correctAnswer: 'A',
    difficulty: 'Easy',
    subject: 'Python',
    topic: 'Function Arguments',
    explanation: '`*args` packs positional arguments into a tuple, while `**kwargs` packs keyword arguments into a dictionary.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_py_9',
    questionText: 'What is a Python Decorator?',
    optionA: 'A function that takes another function as an argument and extends its behavior without modifying it',
    optionB: 'A CSS styling rule for Python Web Frameworks',
    optionC: 'A memory allocation flag for C-extensions',
    optionD: 'A method decorator reserved only for abstract classes',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'Python',
    topic: 'Decorators',
    explanation: 'Decorators wrap a function to modify its behavior (e.g. logging, authentication, timing) using the `@decorator_name` syntax.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_py_10',
    questionText: 'What will `bool([])`, `bool(0)`, and `bool("")` evaluate to in Python?',
    optionA: 'True, True, True',
    optionB: 'False, False, False',
    optionC: 'True, False, False',
    optionD: 'False, True, True',
    correctAnswer: 'B',
    difficulty: 'Easy',
    subject: 'Python',
    topic: 'Truthy & Falsy Values',
    explanation: 'Empty containers `[]`, numeric zero `0`, and empty string `""` are all falsy values in Python boolean evaluation.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },

  // ==========================================
  // JAVA PROGRAMMING (Questions 11 - 20)
  // ==========================================
  {
    id: 'q_jv_11',
    questionText: 'Why is Java called a "Platform Independent" language?',
    optionA: 'Java code is compiled directly into machine code for hardware',
    optionB: 'Java source code compiles into Bytecode which runs on any JVM',
    optionC: 'Java does not require an operating system to run',
    optionD: 'Java source code is interpreted directly without compilation',
    correctAnswer: 'B',
    difficulty: 'Easy',
    subject: 'Java',
    topic: 'JVM & Architecture',
    explanation: 'Java compiler converts `.java` code to `.class` Bytecode, which can run on any OS with a compatible Java Virtual Machine (JVM).',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_jv_12',
    questionText: 'What is the difference between `String`, `StringBuilder`, and `StringBuffer` in Java?',
    optionA: '`String` is mutable; `StringBuilder` and `StringBuffer` are immutable',
    optionB: '`String` is immutable; `StringBuilder` is non-thread-safe (fast); `StringBuffer` is synchronized (thread-safe)',
    optionC: '`StringBuffer` is for primitive types; `StringBuilder` is for objects',
    optionD: 'All three are identical in performance and thread safety',
    correctAnswer: 'B',
    difficulty: 'Medium',
    subject: 'Java',
    topic: 'String Handling & Thread Safety',
    explanation: 'Strings are immutable. StringBuilder provides fast mutable string operations for single threads, whereas StringBuffer is synchronized for multi-thread safety.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_jv_13',
    questionText: 'Does Java support Multiple Inheritance through classes?',
    optionA: 'Yes, using the `extends` keyword with multiple class names',
    optionB: 'No, Java avoids the Diamond Problem in classes, but supports it through Interfaces',
    optionC: 'Yes, but only for abstract classes',
    optionD: 'No, Java does not support inheritance at all',
    correctAnswer: 'B',
    difficulty: 'Easy',
    subject: 'Java',
    topic: 'OOPs & Inheritance',
    explanation: 'Java does not allow multiple class inheritance to avoid ambiguity (Diamond Problem), but a class can implement multiple interfaces.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_jv_14',
    questionText: 'What is the output of `System.out.println(10 + 20 + "SGIP" + 30 + 40);` in Java?',
    optionA: '1020SGIP3040',
    optionB: '30SGIP3040',
    optionC: '30SGIP70',
    optionD: 'Compilation Error',
    correctAnswer: 'B',
    difficulty: 'Medium',
    subject: 'Java',
    topic: 'Operator Precedence & Concatenation',
    explanation: 'Evaluation goes left to right: `10 + 20` = 30. `30 + "SGIP"` = `"30SGIP"`. Once string concatenation starts, subsequent `+` operands are treated as strings: `"30SGIP3040"`.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_jv_15',
    questionText: 'What is the difference between `final`, `finally`, and `finalize` in Java?',
    optionA: '`final` is a modifier; `finally` is a try-catch block; `finalize` is a Garbage Collection method',
    optionB: '`final` is for loops; `finally` is for class declarations; `finalize` is an interface keyword',
    optionC: 'They are exact synonyms used interchangeably',
    optionD: '`finalize` is a constructor keyword',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'Java',
    topic: 'Keywords & Exception Handling',
    explanation: '`final` declares constants/un-overridable methods. `finally` executes cleanup code after try-catch. `finalize()` is called before GC collects an object.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_jv_16',
    questionText: 'Which exception is thrown when an application attempts to use `null` in a case where an object is required?',
    optionA: 'IllegalArgumentException',
    optionB: 'NullPointerException',
    optionC: 'ClassCastException',
    optionD: 'ArrayIndexOutOfBoundsException',
    correctAnswer: 'B',
    difficulty: 'Easy',
    subject: 'Java',
    topic: 'Exception Handling',
    explanation: 'Dereferencing a `null` reference (invoking methods or accessing fields on null) throws a `NullPointerException`.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_jv_17',
    questionText: 'What is Method Overloading vs Method Overriding in Java?',
    optionA: 'Overloading is Compile-time polymorphism (same method name, different parameters); Overriding is Run-time polymorphism (subclass redefines superclass method)',
    optionB: 'Overriding happens in the same class; Overloading happens across packages',
    optionC: 'Overloading requires the `super` keyword',
    optionD: 'Both refer strictly to interface implementations',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'Java',
    topic: 'Polymorphism',
    explanation: 'Method Overloading happens within the same class (different signatures). Method Overriding happens in a child class modifying parent behavior at runtime.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_jv_18',
    questionText: 'What is the default initial capacity and load factor of a HashMap in Java?',
    optionA: 'Capacity 16, Load Factor 0.75',
    optionB: 'Capacity 10, Load Factor 0.50',
    optionC: 'Capacity 32, Load Factor 1.00',
    optionD: 'Capacity 100, Load Factor 0.80',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'Java',
    topic: 'Collections Framework',
    explanation: 'Default initial capacity of `HashMap` is 16 elements, and default load factor is 0.75 (resizes when 75% full).',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_jv_19',
    questionText: 'Which Collection interface allows unique elements and maintains insertion order in Java?',
    optionA: 'HashSet',
    optionB: 'LinkedHashSet',
    optionC: 'TreeSet',
    optionD: 'ArrayList',
    correctAnswer: 'B',
    difficulty: 'Easy',
    subject: 'Java',
    topic: 'Collections Framework',
    explanation: '`LinkedHashSet` maintains a doubly-linked list running through its entries, preserving insertion order while enforcing unique elements.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_jv_20',
    questionText: 'What happens when a thread calls `Thread.sleep(1000)` in Java?',
    optionA: 'The thread releases all object locks and terminates',
    optionB: 'The thread pauses execution for 1 second without releasing locks',
    optionC: 'The thread is destroyed and recreated',
    optionD: 'The JVM exits immediately',
    correctAnswer: 'B',
    difficulty: 'Easy',
    subject: 'Java',
    topic: 'Multithreading',
    explanation: '`Thread.sleep()` causes the current thread to suspend execution for specified milliseconds without giving up monitor locks.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },

  // ==========================================
  // C++ PROGRAMMING (Questions 21 - 28)
  // ==========================================
  {
    id: 'q_cpp_21',
    questionText: 'What is the purpose of virtual functions in C++?',
    optionA: 'To allow compile-time template instantiation',
    optionB: 'To enable Dynamic (Run-time) Polymorphism using virtual function tables (VTABLE)',
    optionC: 'To hide private variables inside a struct',
    optionD: 'To inline function calls for maximum speed',
    correctAnswer: 'B',
    difficulty: 'Medium',
    subject: 'C++',
    topic: 'Virtual Functions & VTABLE',
    explanation: 'Virtual functions allow derived classes to override base class methods, enabling runtime polymorphism via vptr/vtable mechanism.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_cpp_22',
    questionText: 'What is the difference between `new` operator in C++ and `malloc()` in C?',
    optionA: '`new` calls constructors and calculates object size automatically; `malloc()` allocates raw uninitialized memory',
    optionB: '`malloc()` is faster and calls constructors automatically',
    optionC: '`new` can only allocate 100 bytes of memory',
    optionD: '`malloc()` returns a reference while `new` returns a void pointer',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'C++',
    topic: 'Memory Management',
    explanation: '`new` is a C++ operator that allocates memory AND invokes the object constructor. `malloc` is a C function allocating raw bytes.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_cpp_23',
    questionText: 'What is RAII (Resource Acquisition Is Initialization) in C++?',
    optionA: 'A design pattern where resource lifecycle is bound to object lifetime (constructor acquires, destructor releases)',
    optionB: 'A compiler optimization flag for loop unrolling',
    optionC: 'A mechanism to prevent header inclusion loops',
    optionD: 'A syntax style for smart pointers',
    correctAnswer: 'A',
    difficulty: 'Hard',
    subject: 'C++',
    topic: 'RAII & Resource Management',
    explanation: 'RAII guarantees that acquired resources (memory, file handles, locks) are automatically freed when the managing object goes out of scope.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_cpp_24',
    questionText: 'What is the time complexity of searching in `std::map` vs `std::unordered_map` in C++?',
    optionA: '`std::map` is O(log N); `std::unordered_map` is average O(1)',
    optionB: '`std::map` is O(1); `std::unordered_map` is O(N)',
    optionC: 'Both are O(N^2)',
    optionD: 'Both are O(log N)',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'C++',
    topic: 'STL Containers',
    explanation: '`std::map` is implemented as a Red-Black Tree (O(log N)). `std::unordered_map` is implemented as a Hash Table (average O(1)).',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_cpp_25',
    questionText: 'What will happen if a C++ Destructor throws an unhandled exception during stack unwinding?',
    optionA: 'The exception is ignored silently',
    optionB: '`std::terminate()` is called immediately, crashing the program',
    optionC: 'The program restarts automatically',
    optionD: 'Memory is safely deallocated',
    correctAnswer: 'B',
    difficulty: 'Hard',
    subject: 'C++',
    topic: 'Destructors & Exception Safety',
    explanation: 'If a destructor throws an exception while another exception is already active during stack unwinding, C++ calls `std::terminate()`.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_cpp_26',
    questionText: 'What is a Reference in C++ (`int& ref = x;`)?',
    optionA: 'An alias (alternative name) for an existing variable',
    optionB: 'A copy of the variable value',
    optionC: 'A pointer that can be set to nullptr at any time',
    optionD: 'A constant array pointer',
    correctAnswer: 'A',
    difficulty: 'Easy',
    subject: 'C++',
    topic: 'References vs Pointers',
    explanation: 'A reference is an immutable alias for an existing object. It must be initialized when created and cannot be rebound or null.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_cpp_27',
    questionText: 'Which C++ smart pointer provides exclusive ownership of a dynamically allocated object?',
    optionA: '`std::shared_ptr`',
    optionB: '`std::unique_ptr`',
    optionC: '`std::weak_ptr`',
    optionD: '`std::auto_ptr`',
    correctAnswer: 'B',
    difficulty: 'Easy',
    subject: 'C++',
    topic: 'Smart Pointers',
    explanation: '`std::unique_ptr` owns and manages another object through a pointer and disposes of that object when the `unique_ptr` goes out of scope.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_cpp_28',
    questionText: 'What is the output of `std::cout << (5 >> 1);` in C++?',
    optionA: '10',
    optionB: '2',
    optionC: '4',
    optionD: '2.5',
    correctAnswer: 'B',
    difficulty: 'Easy',
    subject: 'C++',
    topic: 'Bitwise Operators',
    explanation: '`5` in binary is `101`. Right shifting by 1 bit (`5 >> 1`) yields `010` in binary, which equals `2` in decimal (integer division by 2).',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },

  // ==========================================
  // C LANGUAGE (Questions 29 - 34)
  // ==========================================
  {
    id: 'q_c_29',
    questionText: 'What is the size of a pointer in a 64-bit operating system in C?',
    optionA: '2 bytes',
    optionB: '4 bytes',
    optionC: '8 bytes',
    optionD: 'Depends on the data type it points to',
    correctAnswer: 'C',
    difficulty: 'Easy',
    subject: 'C',
    topic: 'Pointers & Memory Architecture',
    explanation: 'In a 64-bit architecture, all pointers store 64-bit (8-byte) memory addresses regardless of data type.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_c_30',
    questionText: 'What is the difference between `malloc()` and `calloc()` in C?',
    optionA: '`malloc()` initializes memory to zero; `calloc()` leaves uninitialized garbage values',
    optionB: '`calloc()` initializes allocated memory to zero and takes 2 arguments; `malloc()` leaves garbage values',
    optionC: '`malloc()` is for arrays; `calloc()` is for single integers',
    optionD: 'They are identical functions in stdlib.h',
    correctAnswer: 'B',
    difficulty: 'Medium',
    subject: 'C',
    topic: 'Dynamic Memory Allocation',
    explanation: '`calloc(n, size)` allocates contiguous memory and initializes all bytes to 0, whereas `malloc(size)` leaves memory uninitialized.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_c_31',
    questionText: 'What does a `static` local variable inside a C function do?',
    optionA: 'Restricts the variable to read-only access',
    optionB: 'Retains its value across multiple function calls throughout program execution',
    optionC: 'Allocates the variable on CPU registers for speed',
    optionD: 'Exports the variable to other C translation units',
    correctAnswer: 'B',
    difficulty: 'Medium',
    subject: 'C',
    topic: 'Storage Classes',
    explanation: 'A `static` variable inside a function is initialized once and preserves its state across function invocations.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_c_32',
    questionText: 'What is a Dangling Pointer in C?',
    optionA: 'A pointer pointing to a memory location that has been deallocated (freed)',
    optionB: 'A pointer pointing to NULL',
    optionC: 'A pointer that has not been initialized yet',
    optionD: 'A pointer to a constant integer',
    correctAnswer: 'A',
    difficulty: 'Easy',
    subject: 'C',
    topic: 'Pointer Pitfalls',
    explanation: 'A dangling pointer arises when memory pointed to by a pointer is deallocated without clearing the pointer reference.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_c_33',
    questionText: 'What is Structure Padding in C compilers?',
    optionA: 'Adding empty bytes to align struct members to word boundaries for faster CPU access',
    optionB: 'Compressing struct fields to save RAM space',
    optionC: 'Encrypting struct values in memory',
    optionD: 'Adding security checks to prevent buffer overflow',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'C',
    topic: 'Structures & Data Alignment',
    explanation: 'Compilers insert padding bytes between struct members so each variable aligns with natural memory boundaries (e.g. 4 or 8 bytes).',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_c_34',
    questionText: 'What is the output of: `int a = 5; printf("%d %d", a++, ++a);` in C?',
    optionA: '5 7',
    optionB: '6 7',
    optionC: 'Undefined Behavior (Modifying a variable multiple times without a sequence point)',
    optionD: '5 6',
    correctAnswer: 'C',
    difficulty: 'Hard',
    subject: 'C',
    topic: 'Sequence Points & Undefined Behavior',
    explanation: 'Modifying the same scalar object multiple times within the same sequence point (argument list of printf) results in Undefined Behavior in C.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },

  // ==========================================
  // JAVASCRIPT & WEB TECH (Questions 35 - 40)
  // ==========================================
  {
    id: 'q_js_35',
    questionText: 'What is a Closure in JavaScript?',
    optionA: 'A function bundled together with references to its surrounding lexical state (outer environment)',
    optionB: 'A method to close browser tabs programmatically',
    optionC: 'A syntax error in asynchronous code',
    optionD: 'A garbage collection event',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'JavaScript',
    topic: 'Closures & Scope',
    explanation: 'A closure gives an inner function access to an outer function\'s scope even after the outer function has returned.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_js_36',
    questionText: 'What is the order of execution in the JavaScript Event Loop?',
    optionA: 'Call Stack -> Microtask Queue (Promises) -> Macrotask Queue (setTimeout)',
    optionB: 'Macrotask Queue -> Call Stack -> Microtask Queue',
    optionC: 'Microtask Queue -> Macrotask Queue -> Call Stack',
    optionD: 'All tasks run simultaneously in parallel threads',
    correctAnswer: 'A',
    difficulty: 'Hard',
    subject: 'JavaScript',
    topic: 'Event Loop & Async Architecture',
    explanation: 'JavaScript empties the synchronous Call Stack first, then processes ALL items in the Microtask Queue (Promises), before processing the next Macrotask (setTimeout).',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_js_37',
    questionText: 'What is the difference between `==` and `===` in JavaScript?',
    optionA: '`==` performs type coercion; `===` checks both value AND data type without coercion',
    optionB: '`===` performs type coercion; `==` does not',
    optionC: '`==` is for string comparison only',
    optionD: 'They are identical operators',
    correctAnswer: 'A',
    difficulty: 'Easy',
    subject: 'JavaScript',
    topic: 'Equality Operators',
    explanation: '`==` converts operands to a common type before comparing. Strict equality `===` evaluates to true only if both operands share the same type and value.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_js_38',
    questionText: 'What will `typeof NaN` return in JavaScript?',
    optionA: '"number"',
    optionB: '"nan"',
    optionC: '"undefined"',
    optionD: '"object"',
    correctAnswer: 'A',
    difficulty: 'Easy',
    subject: 'JavaScript',
    topic: 'Types & Quirks',
    explanation: 'In JavaScript specifications, `NaN` (Not-a-Number) is classified as a numeric type, so `typeof NaN` returns `"number"`.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_js_39',
    questionText: 'What is Hoisting in JavaScript?',
    optionA: 'Moving function and variable declarations to the top of their containing scope before code execution',
    optionB: 'Lifting state up in React components',
    optionC: 'Uploading assets to a Content Delivery Network',
    optionD: 'Converting callbacks into async/await functions',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'JavaScript',
    topic: 'Hoisting & TDZ',
    explanation: 'Hoisting is JS behavior where variable/function declarations are allocated in memory during the compile phase before code executes.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_js_40',
    questionText: 'What does `Promise.all([p1, p2, p3])` do if one promise rejects?',
    optionA: 'Immediately rejects with the error of the first rejected promise (fail-fast)',
    optionB: 'Waits for all other promises to resolve and ignores the error',
    optionC: 'Retries the rejected promise 3 times',
    optionD: 'Returns null',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'JavaScript',
    topic: 'Promises & Async Control',
    explanation: '`Promise.all` fails fast: if any promise in the array rejects, the returned promise immediately rejects with that rejection reason.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },

  // ==========================================
  // SQL & DATABASES (Questions 41 - 45)
  // ==========================================
  {
    id: 'q_sql_41',
    questionText: 'What is the difference between `WHERE` and `HAVING` clauses in SQL?',
    optionA: '`WHERE` filters individual rows before grouping; `HAVING` filters group aggregations after `GROUP BY`',
    optionB: '`HAVING` is used for joining tables; `WHERE` is for sorting',
    optionC: '`WHERE` cannot be used with SELECT statements',
    optionD: 'They are identical clauses',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'SQL',
    topic: 'Query Clauses & Aggregation',
    explanation: '`WHERE` filters rows prior to aggregate calculations. `HAVING` filters summarized groups created by the `GROUP BY` clause.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_sql_42',
    questionText: 'What does ACID stand for in Database Transaction Management?',
    optionA: 'Atomicity, Consistency, Isolation, Durability',
    optionB: 'Authentication, Control, Indexing, Data',
    optionC: 'Algorithm, Complexity, Iteration, Dependency',
    optionD: 'Array, Column, Index, Directory',
    correctAnswer: 'A',
    difficulty: 'Easy',
    subject: 'SQL',
    topic: 'ACID Properties',
    explanation: 'ACID properties (Atomicity, Consistency, Isolation, Durability) guarantee reliable database transactions.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_sql_43',
    questionText: 'Which SQL Join returns all records from the left table and matched records from the right table?',
    optionA: 'INNER JOIN',
    optionB: 'LEFT OUTER JOIN',
    optionC: 'RIGHT OUTER JOIN',
    optionD: 'FULL OUTER JOIN',
    correctAnswer: 'B',
    difficulty: 'Easy',
    subject: 'SQL',
    topic: 'Joins',
    explanation: '`LEFT JOIN` returns all rows from the left table, along with matching rows from the right table (filling NULL for missing right rows).',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_sql_44',
    questionText: 'What is Database Normalization (1NF, 2NF, 3NF, BCNF)?',
    optionA: 'The process of organizing data to reduce redundancy and eliminate update/delete anomalies',
    optionB: 'Backing up SQL tables to cloud storage',
    optionC: 'Converting text columns to uppercase',
    optionD: 'Creating duplicate tables for load balancing',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'SQL',
    topic: 'Database Normalization',
    explanation: 'Normalization organizes relational tables to minimize data redundancy and prevent insertion, update, and deletion anomalies.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_sql_45',
    questionText: 'Which data structure is most commonly used for implementing SQL B-Tree Indexes?',
    optionA: 'Self-balancing Search Tree optimized for disk storage I/O',
    optionB: 'Single Linked List',
    optionC: 'Binary Search Heap',
    optionD: 'Stack',
    correctAnswer: 'A',
    difficulty: 'Hard',
    subject: 'SQL',
    topic: 'Indexing Structures',
    explanation: 'B-Trees and B+Trees keep data sorted and allow logarithmic time searches, insertions, and deletions optimized for block storage reads.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },

  // ==========================================
  // PLACEMENT QUANTITATIVE APTITUDE & REASONING (Questions 46 - 50)
  // ==========================================
  {
    id: 'q_apt_46',
    questionText: 'A car covers a distance of 300 km at a speed of 60 km/h and returns at a speed of 40 km/h. What is the average speed for the entire journey?',
    optionA: '50 km/h',
    optionB: '48 km/h',
    optionC: '45 km/h',
    optionD: '52 km/h',
    correctAnswer: 'B',
    difficulty: 'Medium',
    subject: 'Quantitative Aptitude',
    topic: 'Speed Time & Distance',
    explanation: 'Average Speed for equal distances = `2xy / (x + y)` = `2 * 60 * 40 / (60 + 40)` = `4800 / 100` = `48 km/h`.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_apt_47',
    questionText: 'A can complete a work in 12 days, and B can complete the same work in 24 days. How many days will they take if they work together?',
    optionA: '8 days',
    optionB: '10 days',
    optionC: '6 days',
    optionD: '18 days',
    correctAnswer: 'A',
    difficulty: 'Easy',
    subject: 'Quantitative Aptitude',
    topic: 'Work & Time',
    explanation: '1 day work = `1/12 + 1/24 = 3/24 = 1/8`. Together they take `8 days`.',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_apt_48',
    questionText: 'Find the missing term in the number series: 2, 6, 12, 20, 30, ?',
    optionA: '36',
    optionB: '40',
    optionC: '42',
    optionD: '48',
    correctAnswer: 'C',
    difficulty: 'Easy',
    subject: 'Quantitative Aptitude',
    topic: 'Number Series',
    explanation: 'Differences are: +4, +6, +8, +10, so next difference is +12. `30 + 12 = 42` (also `n^2 + n`: 1^2+1=2, 2^2+2=6, 3^2+3=12, 4^2+4=20, 5^2+5=30, 6^2+6=42).',
    marks: 2,
    negativeMarks: 0,
    imported: false
  },
  {
    id: 'q_apt_49',
    questionText: 'If the price of sugar increases by 25%, by what percentage must a household reduce its consumption so as not to increase expenditure?',
    optionA: '25%',
    optionB: '20%',
    optionC: '15%',
    optionD: '30%',
    correctAnswer: 'B',
    difficulty: 'Medium',
    subject: 'Quantitative Aptitude',
    topic: 'Percentages',
    explanation: 'Reduction % = `[R / (100 + R)] * 100` = `[25 / 125] * 100` = `20%`.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  },
  {
    id: 'q_apt_50',
    questionText: 'In a coding test, 60% candidates passed Python, 50% passed Java, and 30% passed both. What percentage of candidates failed both Python and Java?',
    optionA: '20%',
    optionB: '10%',
    optionC: '30%',
    optionD: '15%',
    correctAnswer: 'A',
    difficulty: 'Medium',
    subject: 'Quantitative Aptitude',
    topic: 'Venn Diagrams & Sets',
    explanation: 'Total Passed at least one = `P(Python) + P(Java) - P(Both)` = `60% + 50% - 30%` = `80%`. Percentage failed both = `100% - 80% = 20%`.',
    marks: 4,
    negativeMarks: 1,
    imported: false
  }
];
